alpha/accounts/urls.py
from django.urls import path, re_path, include
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

urlpatterns = [
    path('avatar/', include('avatar.urls')),
    #path('auth/login/', views.user_login, name="login"),
    #path('auth/register/', views.user_register, name="register"),
    path('auth/logout/', views.user_logout, name="logout"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('my-profile/profile/', views.user_my_profile, name="user_my_profile"),
    path('my-profile/orders/', views.user_my_orders, name="user_my_orders"),
    path('my-profile/orders/order<order_id>-info/', views.user_order_info, name="user_order_info"),
    path('my-profile/reviews/', views.user_my_reviews, name="user_my_reviews"),
    path('my-profile/add-address/', views.add_address, name="add_address"),
    path('my-profile/delete-address/', views.delete_address, name="delete_address"),
    path('my-profile/add-personal/', views.add_personal, name="add_personal"),
    path('my-profile/delete-personal/', views.delete_personal, name="delete_personal"),
    path('my-profile/delete-account/', views.delete_account, name="delete_account"),
    path('ajax/delete-review/', views.delete_review, name="delete_review"),

    # password handling urls
    path('password-change/', views.change_password, name='password_change'),
    path('password-set/', views.set_password, name='password_set'),
    path('password-reset/', password_reset, name='password_reset'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('password-reset/complete/', password_reset_complete, name='password_reset_complete'),

    # email handling urls
    path('accounts/email-change/', views.email_change, name='email_change'),

    # after registering new account
    #re_path(r'^registration/', views.after_registration, name="after_registration"),
    #re_path(r'^activation/(?P<activation_key>.+)/$', views.account_activation, name="account_activation"),
]

alpha/alpha/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alpha/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from orders.models import OrderDeliveryArea, OrderDeliveryCity


class Profile(models.Model):
    #this field is required
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='profile', )
    phone = models.CharField(
        null=True,
        blank=True,
        max_length=40, )
    register_date = models.DateField(
        auto_now_add=True,
        null=True, )
    delivery_area = models.OneToOneField(
        OrderDeliveryArea,
        on_delete=models.SET_NULL,
        max_length=150,
        null=True,
        blank=True, )
    delivery_city = models.OneToOneField(
        OrderDeliveryCity,
        on_delete=models.SET_NULL,
        max_length=150,
        null=True,
        blank=True, )
    delivery_address = models.CharField(
        max_length=150,
        null=True,
        blank=True, )
    activation_key = models.CharField(
        null=True,
        blank=True,
        max_length=240, )
    key_expires = models.DateTimeField(
        null=True,
        blank=True, )

    def __str__(self):
        return "Клиент %s" % self.user.username

    def user_email(self):
        return self.user.email

    def user_username(self):
        return self.user.username

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

alpha/products/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(
        max_length=128, 
        blank=True, 
        null=True, 
        default=None)
    description = models.CharField(
        max_length=240,
        blank=True,
        null=True,
        default=None)
    is_active = models.BooleanField(
        default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Категория товара"
        verbose_name_plural = "Категория товаров"

    def get_related_products(self):
        return self.product_set.filter(is_active=True)


class Product(models.Model):
    name = models.CharField(
        max_length=64, 
        blank=True, 
        null=True, 
        default=None)
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        default=0)
    discount = models.DecimalField(
        max_digits=4, 
        decimal_places=2, 
        default=0)
    category = models.ForeignKey(
        ProductCategory, 
        blank=True, 
        null=True, 
        default=None, 
        on_delete=models.CASCADE)
    short_description = models.TextField(
        blank=True, 
        null=True, 
        default=None)
    description = models.TextField(
        blank=True, 
        null=True, 
        default=None)
    description_age = models.TextField(
        blank=True, 
        null=True, 
        default=None)
    description_content = models.TextField(
        blank=True, 
        null=True, 
        default=None)
    description_package_size = models.CharField(
        max_length=64, 
        blank=True, 
        null=True, 
        default=None)
    description_product_size = models.CharField(
        max_length=64, 
        blank=True, 
        null=True, 
        default=None)
    description_package_type = models.CharField(
        max_length=64, 
        blank=True, 
        null=True, 
        default=None)
    description_battery = models.CharField(
        max_length=64, 
        blank=True, 
        null=True, 
        default=None)
    likes = models.ManyToManyField(
        User,
        blank = True,
        related_name='product_likes')
    is_active = models.BooleanField(
        default=True)
    is_new = models.BooleanField(
        default=False)
    is_in_stock = models.BooleanField(
        default=True)
    is_on_demand = models.BooleanField(
        default=False)
    created = models.DateTimeField(
        auto_now_add=True, 
        auto_now=False)
    updated = models.DateTimeField(
        auto_now_add=False, 
        auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
    
    @property
    def product_main_image(self):
        return self.images.get(is_main=True)

    @property
    def product_all_images(self):
        return (self.images.get(is_main=False),) 

    @property
    def price_with_discount(self):
        price_with_discount = self.price - (self.price * self.discount / 100)  
        return "%.2f" % price_with_discount

    def get_absolute_url(self):
        return reverse('product_land', kwargs={'product_id': self.id})

    def get_like_url(self):
        return reverse('like-toggle', kwargs={'product_id': self.id})

    def get_api_like_url(self):
        return reverse('like-api-toggle', kwargs={'product_id': self.id})

class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, 
        blank=True, 
        null=True, 
        default=None, 
        on_delete=models.CASCADE, 
        related_name='images')
    image = models.ImageField(
        upload_to='static/products/img/')
    is_main = models.BooleanField(
        default=False)
    is_active = models.BooleanField(
        default=True)
    created = models.DateTimeField(
        auto_now_add=True, 
        auto_now=False)
    updated = models.DateTimeField(
        auto_now_add=False, 
        auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = "Картинка"
        verbose_name_plural = "Картинки"


class Review(models.Model):
    user = models.ForeignKey(
        User, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL)
    product = models.ForeignKey(
        Product, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL)
    order = models.ForeignKey(
        'orders.Order', 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL)
    text = models.TextField()
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=1)

    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s: оценен на %s пользователем %s" % (self.product.name, self.score, self.user.username)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        ordering = ['-created']

    def get_user(self):
        return self.user

alpha/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile
from orders.models import OrderDeliveryArea, OrderDeliveryCity
from django.utils.translation import ugettext as _


class LoginForm(forms.Form):
    """Form for loggin in"""
    user_email = forms.EmailField(
        required=True)
    user_password = forms.CharField(
        required=True)


class UserRegistrationForm(forms.Form):
    """Form for creating new account/registration"""
    new_user_email = forms.EmailField(
        required=True,
        max_length=240)
    new_user_name = forms.CharField(
        required=True,
        max_length=240)
    password = forms.CharField(
        required=True)
    password_repeat = forms.CharField(
        required=True)

    class Meta:
        model = User

    def clean_username(self):
        username = self.cleaned_data['new_user_email']

    def clean_password_repeat(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_repeat']:
            raise forms.ValidationError('Введенные пароли не совпадают')
        return cd['password_repeat']


class UserChangeFirstnameForm(forms.ModelForm):
    first_name = forms.CharField(label="Имя")

    class Meta:
        model = User
        fields = ('first_name', )

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        if not data:
            raise forms.ValidationError("Это поле не должно быть пустым!")
        return data


class ProfileChangePhoneForm(forms.ModelForm):
    phone = forms.CharField(label="Телефон")

    class Meta:
        model = Profile
        fields = ('phone',)

    def clean_phone(self):
        data = self.cleaned_data['phone']
        if not data:
            raise forms.ValidationError("Это поле не должно быть пустым!")
        return data


class ProfileChangeAddressForm(forms.ModelForm):
    areas_list = OrderDeliveryArea.objects.all()
    cities_list = OrderDeliveryCity.objects.all()

    delivery_area = forms.ChoiceField(
        choices=[('', '-- Выберите область --')] + [(area.id, area.name) for area in areas_list],
        label="Область",
        initial='Выберите область', )
    delivery_city = forms.ChoiceField(
        choices=[('', '-- Выберите город --')] + [(city.id, city.name) for city in cities_list],
        label="Город",
        initial='Выберите город', )
    delivery_address = forms.CharField(
        label="Дополнительная информация: укажите номер и адрес отделения склада перевозчика или Ваш полный почтовый адрес (не требуется заполнять при самовывозе)",
        widget=forms.Textarea, )

    class Meta:
        model = Profile
        fields = ('delivery_address',)


class UserEmailChangeForm(forms.Form):
    """
    A form that lets a user change set their email while checking for a change in the 
    e-mail.
    """
    error_messages = {
        'email_mismatch': _("The two email addresses fields didn't match."),
        'not_changed': _("The email address is the same as the one already defined."),
    }

    new_email1 = forms.EmailField(
        label="Новый Email",
        widget=forms.EmailInput,
    )

    new_email2 = forms.EmailField(
        label="Новый Email еще раз",
        widget=forms.EmailInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserEmailChangeForm, self).__init__(*args, **kwargs)

    def clean_new_email1(self):
        old_email = self.user.email
        new_email1 = self.cleaned_data.get('new_email1')
        if new_email1 and old_email:
            if new_email1 == old_email:
                raise forms.ValidationError(
                    self.error_messages['not_changed'],
                    code='not_changed',
                )
        return new_email1

    def clean_new_email2(self):
        new_email1 = self.cleaned_data.get('new_email1')
        new_email2 = self.cleaned_data.get('new_email2')
        if new_email1 and new_email2:
            if new_email1 != new_email2:
                raise forms.ValidationError(
                    self.error_messages['email_mismatch'],
                    code='email_mismatch',
                )
        return new_email2

alpha/products/forms.py
from django import forms
from .models import *
from django.utils.translation import gettext as _


class ReviewForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, label=_("Отзыв"))
    score = forms.IntegerField(label=_("Оценка"), min_value=1, max_value=5)


    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)


    class Meta:
        model = Review
        fields = ['score', 'text', ]

        widgets = {
            'text': forms.Textarea(
                attrs={'rows': 3, 'placeholder': _('Комментарий')}),
        }

alpha/templates/accounts/change_email.html
{% extends 'base.html' %}

{% load i18n %}
{% load widget_tweaks %}

{% block content %}

<section class="section-header"></section>
<section class="section-navigation">
    <div class="container">
        <div class="row d-flex">
            <div class="col-lg-7 order-2 order-lg-1">
                <div class="section-heading justify-content-lg-start justify-content-center">
                    <h1>E-mail адреса</h1>
                </div>
            </div>
            <div class="col-lg-5 text-right order-1 order-lg-2">
                <ul class="breadcrumb justify-content-lg-end justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">На главную</a>
                    </li>
                    <li class="breadcrumb-item active">
                        E-mail адреса
                    </li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="section-email">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="footer-text text-center">
                    <p>Здесь можно изменить ваш текущий электронный адрес.</p>
                    {% if user.email %}
                    <p>Следующий e-mail адрес прикреплен к Вашему аккаунту: <span style="color: #6E52E5; font-weight: bolder;">{{ user.email }}</span></p>
                    {% else %}
                    <p>Внимание! На данный момент у Вас нет привязанных e-mail адресов. Чтобы получать уведомления сайта при оформлении заказов, а также для сброса/восстановления вашего пароля, необходимо добавить электронный адрес!</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- End Row -->
        <div class="row">
            <div class="col-lg-3 col-md-3"></div>
            <div class="col-lg-6 col-md-6 col-sm-12" style="margin-top: 40px;">
                {% if user.email %}
                <form action="{% url 'email_change' %}" method="post">
                {% csrf_token %}
                    <div class="wrap-input100">
                        <label for="{{ form.new_email1.auto_id }}" class="label-input100">{{ form.new_email1.label }}</label>
                        {% render_field form.new_email1|add_class:"input100" %}
                        <span class="focus-input100"></span>
                    </div>
                    <div class="wrap-input100">
                        <label for="{{ form.new_email2.auto_id }}" class="label-input100">{{ form.new_email2.label }}</label>
                        {% render_field form.new_email2|add_class:"input100" %}
                        <span class="focus-input100"></span>
                    </div>
                    <div class="text-center">
                        <button class="btn submit-btn" type="submit" name="action" value="{% trans 'Change Email' %}"/>Изменить email</button>
                    </div>
                </form>
                {% endif %}
            </div>
            <div class="col-lg-3 col-md-3"></div>
        </div>
    </div>
</section>
{% endblock %}

alpha/templates/accounts/my_profile.html
{% extends 'base.html' %}
{% load static %}

{% block dashboard %}

<section class="section-header"></section>
<section class="section-navigation">
    <div class="container">
        <div class="row d-flex">
            <div class="col-lg-7 order-2 order-lg-1">
                <div class="section-heading justify-content-lg-start justify-content-center">
                    <h1>Профиль</h1>
                </div>
            </div>
            <div class="col-lg-5 text-right order-1 order-lg-2">
                <ul class="breadcrumb justify-content-lg-end justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">На главную</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Профиль
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="section-my-profile">
    <div class="container">
		<div class="row">
			<div class="col-12">
				<div class="footer-text text-center">
					<p>Добро пожаловать в личный кабинет! Здесь можно изменить персональную информацию, учётные данные, а также просмотреть историю заказов и отзывов.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-3"></div>
			<div class="col-12 col-sm-12 col-md-3 col-lg-3">
				<div class="single-dashboard-item">
					<div class="dashboard-image">
						<img src="{% static 'img/accounts/dashboard-orders.jpg' %}" alt="">
						<div class="dashboard-hover-effects">
							<div class="dashboard-goto-icon">
								<a href="{% url 'user_my_orders' %}">Перейти</a>
							</div>
						</div>
					</div>
					<div class="dashboard-text">
						<h4>Мои заказы</h4>
						<p style="font-weight: 400;">Посмотреть статус и историю заказов</p>
					</div>
				</div>
			</div>
			<div class="col-12 col-sm-12 col-md-3 col-lg-3">
				<div class="single-dashboard-item">
					<div class="dashboard-image">
						<img src="{% static 'img/accounts/dashboard-credentials.jpg' %}" alt="">
						<div class="dashboard-hover-effects">
							<div class="dashboard-goto-icon">
								<a href="{% url 'user_my_profile' %}">Перейти</a>
							</div>
						</div>
					</div>
					<div class="dashboard-text">
						<h4>Мой профиль</h4>
						<p style="font-weight: 400;">Редактировать учетные данные, изменить пароль или удалить аккаунт</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-3"></div>
		</div>
    </div>
    <!-- End Container -->
</section>
<!-- End Section Dashboard -->

{% endblock dashboard %}

alpha/templates/accounts/user_my_reviews.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load products_tags %}

{% block content %}
<section class="section-header"></section>
<section class="section-navigation">
    <div class="container">
        <div class="row d-flex">
            <div class="col-lg-7 order-2 order-lg-1">
                <div class="section-heading justify-content-lg-start justify-content-center">
                    <h1>Отзывы о товарах</h1>
                </div>
            </div>
            <div class="col-lg-5 text-right order-1 order-lg-2">
                <ul class="breadcrumb justify-content-lg-end justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">На главную</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'my_profile' %}">Профиль</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Отзывы о товарах
                    </li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
		<div class="row">
            <div class="col">
                <div class="footer-text text-center">
                    <p>В этом разделе Вы можете получить доступ ко всем Вашим отзывам на товары. Вы можете изменить их текст или удалить их</p>
                    {% if not feedbacks %}
                    <p>Пока Вы еще не оставляли отзывов о наших товарах</p>
                    {% endif %}
                </div>
            </div>
		</div>
		<!-- End Row -->
        <div class="row">
            <div class="col-12 order-box mt-0 mb-lg-0">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="text-center">
                            <tr>
                               <th class="border-top-0">Товар</th>
                               <th class="border-top-0">Дата</th>
                               <th class="border-top-0">Оценка</th>
                               <th class="border-top-0">Отзыв</th>
                               <th class="border-top-0">Действие</th>
                            </tr>
                        </thead>
                        {% for feedback in feedbacks %}
                        <tbody>
                            <th><a href="{% url 'product_land' feedback.product.id %}">{{ feedback.product.name }}</a></th>
                            <td>{{ feedback.created }}</td>
                            <td class="text-center star-rating">{% for item in feedback.score|times %}
                                    <i class="ion-ios-star"></i>
                                {% endfor %}</td>
                            <td class="text-justify">
                                {{ feedback.text }}
                                {% if feedback.updated %}
                                <br><i>(Отредактировано: {{ feedback.updated }})</i>
                                {% endif %}
                            </td>
                            <td>
                                <a href="" class="button-review-view" id="change_feedback_button" data-toggle="modal" data-target="#changefeedbackModal" data-review_id="{{ feedback.id }}" data-feedback_score="{{ feedback.score }}" data-feedback_text="{{ feedback.text }}" data-feedback_product="{{ feedback.product.name }}">Изменить</a>
                                <a class="button-review-view" href="" data-toggle="modal" data-target="#deletefeedbackModal" data-feedback_id="{{ feedback.id }}">Удалить</a>
                            </td>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Container -->
</section>
<!-- End Section Orders -->
<!-- Modal Change Feedback -->
<div class="container">
    <div class="row">
        <div class="col-lg-7 mx-auto">
            <div class="modal fade" id="changefeedbackModal" tabindex="-1" role="dialog" aria-labelledby="addfeedbackModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="changefeedbackModalLabel">Редактирование отзыва</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="col">
                                <div class="review-form-container">
                                    <form method="POST" action="." id="feedback_change_form">
                                    {% csrf_token %}
                                        <p class="change-feedback-product"></p>
                                        <input type="hidden" id="review_id" />
                                        <div class="wrap-input100">
                                            <label for="{{ form.score.auto_id }}" class="label-input100">{{ form.score.label }}</label>
                                            {% render_field form.score|add_class:"input100" %}
                                            <span class="focus-input100"></span>
                                        </div>
                                        <div class="wrap-input100">
                                            <label for="{{ form.text.auto_id }}" class="label-input100">{{ form.text.label }}</label>
                                            {% render_field form.text|add_class:"input100" %}
                                            <span class="focus-input100"></span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button form="feedback_change_form" class="btn submit-btn" type="submit">Редактировать</button>
                            <button type="button" class="btn submit-btn" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Delete Feedback -->
<div class="container">
    <div class="row">
        <div class="col-lg-7 mx-auto">
            <div class="modal fade" id="deletefeedbackModal" tabindex="-1" role="dialog" aria-labelledby="addfeedbackModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deletefeedbackModalLabel">Удаление отзыва</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form id="review_delete_form" action="{% url 'delete_review' %}">{% csrf_token %}
                                <input id="delete_input" type="hidden" />
                            </form>
                            <form action="{% url 'user_my_reviews' %}" id="go_back_form"></form>
                            <p>Вы действительно желаете удалить данный отзыв? (После этого возможно будет оставить новый отзыв на странице товара)</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn submit-btn" data-dismiss="modal">Отменить</button>
                            <button type="submit" class="btn submit-btn btn-delete">Удалить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
    <script>
        $('#changefeedbackModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var review_id = button.data('review_id');
            var product = button.data('feedback_product');
            var score = button.data('feedback_score');
            var text = button.data('feedback_text');
            var modal = $(this);
            modal.find('#review_id').attr('value', review_id);
            modal.find('#review_id').attr('name', 'review_id');
            modal.find('.change-feedback-product').text('Товар: ' + product);
            modal.find('#id_text').attr('value', text);
            modal.find('#id_text').text(text);
            modal.find('#id_score').attr('value', score);
            modal.find('#id_score').text(score);
        })
    </script>
    <script>
        $('#deletefeedbackModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var feedback_id = button.data('feedback_id');
            var modal = $(this);
            modal.find('#delete_input').attr('value', feedback_id);
        })
    </script>
    <script>
        // My Profile Reviews Page review delete button
        $('#deletefeedbackModal .btn-delete').on('click', function(e) {
            e.preventDefault();
            var form = $('#review_delete_form');
            var url = form.attr('action');
            var csfr_token = $('#review_delete_form [name="csrfmiddlewaretoken"]').val();
            var feedback_id = $('#delete_input').val();
            var redirect_url = $('#go_back_form').attr('action');
            data = {}
            data["csrfmiddlewaretoken"] = csfr_token;
            data["feedback_id"] = feedback_id;
            $.ajax({
                url: url,
                type: 'POST',
                data: data,
                cache: true,
                success: function(data) {
                    window.location.href = redirect_url;
                }
            });
        });
    </script>
{% endblock javascript %}